server:
  port: 8083
spring:
  application:
    name: card-service
  datasource:
    url: jdbc:postgresql://localhost:5432/andersendb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

